import keyMirror from 'keymirror';

export const LOADED_USER_RECEIVED = 'LOADED_USER_RECEIVED';
export const CREATED_USER_RECEIVED = 'CREATED_USER_RECEIVED';
export const EDITED_USER_RECEIVED = 'EDITED_USER_RECEIVED';
export const DELETED_USER_RECEIVED = 'DELETED_USER_RECEIVED';

export const TRANSACTION_INITIALIZE = 'TRANSACTION_INITIALIZE';
export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST';
export const TRANSACTION_REJECTED = 'TRANSACTION_REJECTED';
export const TRANSACTION_RESOLVED = 'TRANSACTION_RESOLVED';

export const AUTH_STATUS_RECEIVED = 'AUTH_STATUS_RECEIVED';
export const AUTH_STATUS_CHECK_REQUEST = 'AUTH_STATUS_CHECK_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESULT_RECEIVED = 'LOGIN_RESULT_RECEIVED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RESULT_RECEIVED = 'LOGOUT_RESULT_RECEIVED';