import keyMirror from 'keymirror';

export const LOADED_USER_RECEIVED = 'LOADED_USER_RECEIVED';
export const CREATED_USER_RECEIVED = 'CREATED_USER_RECEIVED';
export const EDITED_USER_RECEIVED = 'EDITED_USER_RECEIVED';
export const USER_PASSWORD_EDIT_COMPLETE = 'USER_PASSWORD_EDIT_COMPLETE';
export const DELETED_USER_RECEIVED = 'DELETED_USER_RECEIVED';

export const LOADED_CATEGORY_RECEIVED = 'LOADED_CATEGORY_RECEIVED';
export const CREATED_CATEGORY_RECEIVED = 'CREATED_CATEGORY_RECEIVED';
export const EDITED_CATEGORY_RECEIVED = 'EDITED_CATEGORY_RECEIVED';
export const DELETED_CATEGORY_RECEIVED = 'DELETED_CATEGORY_RECEIVED';

export const LOADED_BLOG_RECEIVED = 'LOADED_BLOG_RECEIVED';
export const CREATED_BLOG_RECEIVED = 'CREATED_BLOG_RECEIVED';
export const EDITED_BLOG_RECEIVED = 'EDITED_BLOG_RECEIVED';
export const DELETED_BLOG_RECEIVED = 'DELETED_BLOG_RECEIVED';

export const LOADED_POST_RECEIVED = 'LOADED_POST_RECEIVED';
export const CREATED_POST_RECEIVED = 'CREATED_POST_RECEIVED';
export const EDITED_POST_RECEIVED = 'EDITED_POST_RECEIVED';
export const DELETED_POST_RECEIVED = 'DELETED_POST_RECEIVED';

export const LOADED_SETTING_RECEIVED = 'LOADED_SETTING_RECEIVED';
export const EDITED_SETTING_RECEIVED = 'EDITED_SETTING_RECEIVED';

export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST';
export const TRANSACTION_REJECTED = 'TRANSACTION_REJECTED';
export const TRANSACTION_RESOLVED = 'TRANSACTION_RESOLVED';
export const TRANSACTION_FINISHED = 'TRANSACTION_FINISHED';

export const AUTH_STATUS_RECEIVED = 'AUTH_STATUS_RECEIVED';
export const AUTH_STATUS_CHECK_REQUEST = 'AUTH_STATUS_CHECK_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESULT_RECEIVED = 'LOGIN_RESULT_RECEIVED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RESULT_RECEIVED = 'LOGOUT_RESULT_RECEIVED';

export const LOADED_FRONT_BLOG_RECEIVED = 'LOADED_FRONT_BLOG_RECEIVED';