export const USERS_LOAD_REQUEST = 'USERS_LOAD_REQUEST';
export const LOADED_USER_RECEIVED = 'LOADED_USER_RECEIVED';
export const USERS_EDIT_REQUEST = 'USERS_EDIT_REQUEST';
export const EDITED_USER_RECEIVED = 'EDITED_USER_RECEIVED';
export const USER_EDIT_ERROR_RECEIVED = 'USER_EDIT_ERROR_RECEIVED';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const AUTH_STATUS_RECEIVED = 'AUTH_STATUS_RECEIVED';
export const AUTH_STATUS_CHECK_REQUEST = 'AUTH_STATUS_CHECK_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESULT_RECEIVED = 'LOGIN_RESULT_RECEIVED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RESULT_RECEIVED = 'LOGOUT_RESULT_RECEIVED';