export const LOADED_FRONT_BLOG_RECEIVED = 'LOADED_FRONT_BLOG_RECEIVED';
export const LOADED_PUBLIC_CATEGORIES_RECEIVED = 'LOADED_PUBLIC_CATEGORIES_RECEIVED';
export const LOADED_PUBLIC_POSTS_RECEIVED = 'LOADED_PUBLIC_POST_RECEIVED';
export const LOADED_PUBLIC_SINGLE_POST_RECEIVED = 'LOADED_PUBLIC_SINGLE_POST_RECEIVED';
export const LOADED_THEMES_RECEIVED = 'LOADED_THEMES_RECEIVED';

export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST';
export const TRANSACTION_REJECTED = 'TRANSACTION_REJECTED';
export const TRANSACTION_RESOLVED = 'TRANSACTION_RESOLVED';
export const TRANSACTION_FINISHED = 'TRANSACTION_FINISHED';